name: Bug report
description: Report an issue related to the Sidebar Organizer plugin
labels: ['bug']
assignees: ['ngocjohn']

body:
  - type: markdown
    attributes:
      value: |
        Make sure you are running the [latest version of Sidebar Organizer][releases] before reporting an issue.

        Thanks for taking the time to fill out this bug report! ðŸ› ï¸

        [releases]: https://github.com/ngocjohn/sidebar-organizer/releases
  - type: checkboxes
    attributes:
      label: Checklist
      description: Please verify that you have followed these steps
      options:
        - label: I have updated to the latest version
          required: true
        - label: I have plugin path in configuration file [extra-module-url](https://github.com/ngocjohn/sidebar-organizer?tab=readme-ov-file#install-the-plugin)
          required: true
  - type: markdown
    attributes:
      value: |
        ## The problem
  - type: input
    id: summary
    attributes:
      label: Short summary ðŸ“
      description: A short summary of the bug
      placeholder: "e.g., The sidebar doesn't collapse on mobile devices"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Detailed description ðŸ“‹
      description: A detailed description of the bug
      placeholder: 'Describe the bug in detail, including steps to reproduce, expected behavior, and actual behavior.'
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: input
    validations:
      required: true
    attributes:
      label: What version of Sidebar Organizer are you using?
      placeholder: e.g., 1.2.3
      description: >
        Can be found in [hacs plugin page](https://my.home-assistant.io/redirect/hacs_repository/?owner=ngocjohn&repository=sidebar-organizer&category=plugin) (top left corner). Or in the plugin configuration dialog header.
  - type: input
    validations:
      required: false
    attributes:
      label: What version of Home Assistant Core has the issue?
      placeholder: core-
      description: >
        Can be found in: [Settings -> About](https://my.home-assistant.io/redirect/info/).
  - type: input
    attributes:
      label: In which browser are you experiencing the issue?
      placeholder: Google Chrome 88.0.4324.150
      description: >
        Provide the full name and don't forget to add the version!
  - type: input
    attributes:
      label: Which operating system are you using to run this browser?
      placeholder: macOS Big Sur (1.11)
      description: >
        Don't forget to add the version!
  - type: markdown
    attributes:
      value: |
        # Details
  - type: textarea
    attributes:
      label: Problem-relevant plugin configuration
      description: >
        An example configuration that caused the problem for you, e.g., the YAML
        configuration of the plugin. Please make sure to remove any sensitive
        information before sharing.
      placeholder: >
        ```yaml
        bottom_items: [],
        custom_groups: {},
        hide_header_toggle: false,
        default_collapsed: [],
        hidden_items: [],
        new_items: [],
        ```
      render: yaml
  - type: textarea
    attributes:
      label: JavaScript errors shown in your browser console/inspector
      description: >
        If you come across any JavaScript or other error logs, e.g., in your
        browser console/inspector please provide them.
      render: txt
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information, use the field below.
        Please note, you can attach screenshots or screen recordings here, by
        dragging and dropping files in the field below.
