name: Update Bug Report Template

on:
  workflow_dispatch:

jobs:
  update-template:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Decode script from secret
        run: |
          echo "${{ secrets.UPDATE_SCRIPT_B64 }}" | base64 -d > update-template.js

      - name: Install dependencies
        run: npm install axios

      - name: Run update script
        run: node update-template.js

      - name: Push changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add .github/ISSUE_TEMPLATE/BUG_REPORT.yml
          git commit -m "Update Bug Report Template" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
